#  Copyright (c) 2026 Metaform Systems, Inc
#  SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Namespace
metadata:
  name: vault-e2e-test
  labels:
    name: vault-e2e-test
    purpose: e2e-testing
